### ISSUE TITLE
Can't connect to MySQL server

### ISSUE THREAD

**Issue by qingyuanyou** [e-m-b-a/embark#140] opened 2023-07-27 10:03 UTC
**Describe the bug**
Hi Teams,

please help me with installation issue.
when run the check_db.
I got the error as below,
![image](https://github.com/e-m-b-a/embark/assets/20557108/3d3e6c3e-bee4-4410-8208-36e81a09a94f)

what I did:
I reset the pwd and it can be connected successfully in  mysql docker
and make sure it has correct connection information when check_db.
the information as below,
![image](https://github.com/e-m-b-a/embark/assets/20557108/94a828e7-ca87-41c1-8eea-2095130b71db)
![image](https://github.com/e-m-b-a/embark/assets/20557108/bc412ea8-f78f-44d0-886e-2dd4606900ab)
![image](https://github.com/e-m-b-a/embark/assets/20557108/0f74ada7-a889-40db-b724-464a02957cd4)

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04

**Comment by BenediktMKuehne** [comment] 2023-07-27 12:54
I'm really sorry about this, I think this has something to do with a timing issue.

The mysql-container starts but isn't responsive for the next ~40 seconds (dependingon the system), so even the retry times out.

I'll go look for a proper fix for this.
Will tell you once I have one

**Comment by qingyuanyou** [comment] 2023-07-28 10:59
Hello Team,

Thanks for your support.
So far, I re-ran the project under the new directory and checked the database connection successfully at the second check.
There is another issue I met that cannot pipenv install with Pipfile. 
In case other has the same issue, the solution is as follows ,
`cd /var/www/`
`sudo pipenv run pip install <packages>`

**Comment by BenediktMKuehne** [comment] 2023-07-28 11:20
In most cases where `pipenv install ` fails the issue is a working network connection or proxy configuration.
If the bug/issue you've encountered is actually with the current Pipfile - if it's outdated or not working for some reason - please submit another separate issue with some screenshots/context.

Thank you, hope this helps

**Closed as completed** 2023-08-22 12:48 UTC
Labels: Installation
